const score = [
  {
    name: "Classical Vocal Solo (Hindustani/Carnatic)",
    first: { collegeId: 0, points: 0 },
    second: { collegeId: 0, points: 0 },
    third: { collegeId: 0, points: 0 },
  },
  {
    name: "Classical Instrumental Solo (Percussion Tala Vadya)",
    first: { collegeId: 0, points: 0 },
    second: { collegeId: 0, points: 0 },
    third: { collegeId: 0, points: 0 },
  },
  {
    name: "Classical Instrumental Solo (Non-Percussion Swara Vadya)",
    first: { collegeId: 0, points: 0 },
    second: { collegeId: 0, points: 0 },
    third: { collegeId: 0, points: 0 },
  },
  {
    name: "Light Vocal Solo (Indian)",
    first: { collegeId: 0, points: 0 },
    second: { collegeId: 0, points: 0 },
    third: { collegeId: 0, points: 0 },
  },
  {
    name: "Western Vocal Solo",
    first: { collegeId: 0, points: 0 },
    second: { collegeId: 0, points: 0 },
    third: { collegeId: 0, points: 0 },
  },
  {
    name: "Group Song (Indian)",
    first: { collegeId: 0, points: 0 },
    second: { collegeId: 0, points: 0 },
    third: { collegeId: 0, points: 0 },
  },
  {
    name: "Group Song (Western)",
    first: { collegeId: 0, points: 0 },
    second: { collegeId: 0, points: 0 },
    third: { collegeId: 0, points: 0 },
  },
  {
    name: "Folk Orchestra",
    first: { collegeId: 0, points: 0 },
    second: { collegeId: 0, points: 0 },
    third: { collegeId: 0, points: 0 },
  },
  {
    name: "Folk / Tribal Dance",
    first: { collegeId: 0, points: 0 },
    second: { collegeId: 0, points: 0 },
    third: { collegeId: 0, points: 0 },
  },
  {
    name: "Classical Dance Solo",
    first: { collegeId: 0, points: 0 },
    second: { collegeId: 0, points: 0 },
    third: { collegeId: 0, points: 0 },
  },
  {
    name: "Quiz",
    first: { collegeId: 0, points: 0 },
    second: { collegeId: 0, points: 0 },
    third: { collegeId: 0, points: 0 },
  },
  {
    name: "Debate",
    first: { collegeId: 0, points: 0 },
    second: { collegeId: 0, points: 0 },
    third: { collegeId: 0, points: 0 },
  },
  {
    name: "Elocution",
    first: { collegeId: 0, points: 0 },
    second: { collegeId: 0, points: 0 },
    third: { collegeId: 0, points: 0 },
  },
  {
    name: "Skit",
    first: { collegeId: 0, points: 0 },
    second: { collegeId: 0, points: 0 },
    third: { collegeId: 0, points: 0 },
  },
  {
    name: "Mime",
    first: { collegeId: 0, points: 0 },
    second: { collegeId: 0, points: 0 },
    third: { collegeId: 0, points: 0 },
  },
  {
    name: "Mimicry",
    first: { collegeId: 0, points: 0 },
    second: { collegeId: 0, points: 0 },
    third: { collegeId: 0, points: 0 },
  },
  {
    name: "One Act Play",
    first: { collegeId: 0, points: 0 },
    second: { collegeId: 0, points: 0 },
    third: { collegeId: 0, points: 0 },
  },
  {
    name: "Collage",
    first: { collegeId: 0, points: 0 },
    second: { collegeId: 0, points: 0 },
    third: { collegeId: 0, points: 0 },
  },
  {
    name: "Rangoli",
    first: { collegeId: 0, points: 0 },
    second: { collegeId: 0, points: 0 },
    third: { collegeId: 0, points: 0 },
  },
  {
    name: "Cartooning",
    first: { collegeId: 0, points: 0 },
    second: { collegeId: 0, points: 0 },
    third: { collegeId: 0, points: 0 },
  },
  {
    name: "Installation",
    first: { collegeId: 0, points: 0 },
    second: { collegeId: 0, points: 0 },
    third: { collegeId: 0, points: 0 },
  },
  {
    name: "Poster Making",
    first: { collegeId: 0, points: 0 },
    second: { collegeId: 0, points: 0 },
    third: { collegeId: 0, points: 0 },
  },
  {
    name: "Clay Modelling",
    first: { collegeId: 0, points: 0 },
    second: { collegeId: 0, points: 0 },
    third: { collegeId: 0, points: 0 },
  },
  {
    name: "On Spot Painting",
    first: { collegeId: 0, points: 0 },
    second: { collegeId: 0, points: 0 },
    third: { collegeId: 0, points: 0 },
  },
  {
    name: "Spot Photography",
    first: { collegeId: 0, points: 0 },
    second: { collegeId: 0, points: 0 },
    third: { collegeId: 0, points: 0 },
  },
];

export default score;
