const rules = {
  music: [
    {
      name: "Classical Vocal Solo (Hindustani/Karnataka)",
      rules: [
        "Only one entry per institution is allowed.",
        "Duration of performance 10 – 15 minutes.",
        "Time for stage /Instruments setting is maximum 5 minutes (karaoke not allowed).",
        "Maximum number of accompanists allowed is two.",
        "Item can be presented in either Hindustani or Karnataka style.",
        "Cinema songs are not allowed under this item.",
        "Sufficient thought and care must be exercised in the choice of Raga and composition.",
        "Judgment will be based on the qualities like, taal, selection of raga, composition and general impression.",
        "The participating team must report to the In-Charge of the competition at least two hours before the presentation of the play.",
        "Decision of the panel of judges will be final and binding upon all.",
      ],
    },
    {
      name: "Classical Instrumental Solo (Percussion Tal Vadya)",
      rules: [
        "Only one entry per institution is allowed.",
        "Duration of performance 10 – 15 minutes.",
        "Time for stage /Instruments setting is maximum 5 minutes.",
        " Maximum number of accompanists allowed is two.",
        "Participants must bring their own instruments, Casio not allowed.",
        "Item can be presented in either Hindustani or Karnataka style.",
        "Judgment will be based on the qualities like, taal, selection of raga, composition and general impression.",
        "The participating team must report to the In-Charge of the competition at least two hours before the presentation of the play.",
        "Decision of the panel of judges will be final and binding upon all.",
      ],
    },
    {
      name: "Light Vocal (India)",
      rules: [
        "Only one entry per Institution is allowed.",
        "Time for Stage /Instruments setting is maximum 2 minutes. (karaoke not allowed).",
        "Maximum number of accompanists allowed is two.",
        "Duration of the song shall be between 4 to 6 minutes.",
        "Only non-film songs/ Geet/ Ghazal/ Bhajan/ Shabad and abhanges can be presented.",
        "Judgment will be made on the qualities like swara, taal, selection of raga, composition and general impression.",
        "The participating team must report to the In-Charge of the competition at least two hours before the presentation of the play.",
        "Decision of the panel of judges will be final and binding upon all.",
      ],
    },
    {
      name: "Classical Instrumental Solo (Non-Precussion Swar Vadya)",
      rules: [
        "Only one entry per Institution is allowed.",
        "Time for Stage /Instruments setting is maximum 2 minutes. (karaoke not allowed).",
        "Maximum number of accompanists allowed is two.",
        "Duration of the song shall be between 4 to 6 minutes.",
        "Only non-film songs/ Geet/ Ghazal/ Bhajan/ Shabad and abhanges can be presented.",
        "Judgment will be made on the qualities like swara, taal, selection of raga, composition and general impression.",
        "The participating team must report to the In-Charge of the competition at least two hours before the presentation of the play.",
        "Decision of the panel of judges will be final and binding upon all.",
      ],
    },
    {
      name: "Western Vocal (Solo)",
      rules: [
        "Only one entry per Institution is allowed.",
        "Time for Stage /Instruments setting is maximum 2 (two) minutes.",
        "The number of accompanists allowed shall not be more than two.",
        "Duration of the song shall be between 4 to 6 minutes.",
        "Language of the song shall only be English.",
        "No karaoke or programmed music allowed.",
        "The participating team must report to the In-Charge of the competition at least two hours before the presentation of the play.",
        "Decision of the panel of judges will be final and binding upon all.",
      ],
    },
    {
      name: "Group Song (Indian)",
      rules: [
        "Only one entry per Institution is allowed.",
        "A team has to present two songs, one patriotic and another will be a folk song.",
        "Maximum 6(six) singers in a group and number of accompanists playing instruments shall be 3(three).",
        "The group songs should be taken from Indian songs which can be in regional language.",
        "No film songs should be presented as group song.",
        "Maximum time allowed for the group song is 10 minutes, which does not include setting time. The setting time for a group shall not exceed 4 minutes.",
        "The participating team must report to the In-Charge of the competition at least two hours before the presentation of the play.",
        "Decision of the panel of judges will be final and binding upon all.",
      ],
    },
    {
      name: "Group Song (Western)",
      rules: [
        "Only one entry per institution is allowed.",
        "Maximum 6 singers in a group and number of accompanists playing instruments shall be 3.",
        "The group songs should be taken from English language.",
        "Maximum time allowed for the group song is 10 minutes, which does not include setting time. The setting time for a group shall not exceed 5 minutes.",
        "Judging of these items will be on the basis of quality of singing only and not on makeup, costumes and action of the team.",
        "The participating team must report to the In-Charge of the competition at least two hours before the presentation of the play.",
        "Decision of the panel of judges will be final and binding upon all.",
      ],
    },
    {
      name: "Flok Orchestra",
      rules: [
        "Only one entry/team per institution is allowed.",
        "The team shall consist of up to 12 participants.",
        "Time for Stage /Instruments setting is maximum 5(five) minutes.",
        "The duration of the performance will be a minimum for 10 minute and a maximum for 15 minutes.",
        "Up to three professional accompanists are allowed who should be in different dress from the student participants so that they could be easily identified.",
        "The professional accompanist shall sit/stand separately from the participants and shall not lead the team.",
        [
          "The team may present preferably those folk tunes which are recognized as folk tunes of the distict to which the college belongs.",
          [
            "Vocal singing is not allowed, however teams may use vocal punctuations as a chorus.",
            "Use of musical instruments backed up by electrical power/amplifier etc., are not allowed.",
          ],
        ],
        "The participating team must report to the In-Charge of the competition at least two hours before the presentation of the play.",
        "Decision of the panel of judges will be final and binding upon all.",
      ],
    },
  ],
  dance: [
    {
      name: "Folk / Tribal Dance",
      rules: [
        "Only one entry per institution is allowed.",
        "Maximum 10 participants allowed per team.",
        "The number of accompanists permissible is five.",
        "The dance can be either ethnic or a folk dance (Indian Style) but not a classical one.",
        "Duration of dance should not be more than 10 – 15 minutes.",
        "Three copies of a brief note giving the theme and the text of song if any, is to be submitted along with the entry form at the time of registration.",
        "The participating team will be responsible for removal of their sets/properties, etc., immediately after the completion of their performance.",
        "Judgment will be based on the basis of Rhythm, Formation, Expression, Costumes, Make-up, Sets and on overall effect.",
        "Time for sets/instruments setting is maximum 5 minutes.",
        "The folk dance: pre-recorded CD’s/Pen drive may be used.",
        "The participating team must report to the In-Charge of the competition at least two hours before the presentation of the play.",
        "Decision of the panel of judges will be final and binding upon all.",
      ],
    },
    {
      name: "Classical Dance (Indian)",
      rules: [
        "Only one entry per institution is allowed.",
        "Maximum 1 participant allowed per team.",
        "The classical dance can be from any of the approved schools of dance such as Kathak, Kathakali, Bharat Natyam, Sattriya, Manipuri, Kuchipudi, Mohiniattam, Odissi, etc.",
        "Duration of dance should not be more than 10 – 15 minutes.",
        "Maximum two accompanists are permissible.",
        "Classical dance solo: pre-recorded CD’s/Pen drive may be used.",
        "Judgment will be based on the qualities like Tal, Technique, Rhythm, Abhinaya or Expression, Costumes, Footwork and general impression.",
        "Three copies of a brief note on the description of dance story involved in it, if any, and of the accompanying song with its meaning in Hindi or English must be submitted at the time of registration.",
        "Time for sets/instruments setting is maximum 5 minutes.",
        "The participating team must report to the In-Charge of the competition at least two hours before the presentation of the play.",
        "Decision of the panel of judges will be final and binding upon all.",
      ],
    },
  ],
  literary: [
    {
      name: "Quiz",
      rules: [
        "Each Institute can send a team of 3 students.",
        "There will be a written preliminary round and teams will be elected for the final.",
        "Finals will be oral with audio visual questions.",
        "The specific rules regarding evaluation procedure, time to reply a particular answer and the type of round will be given before the actual start of the competition.",
        "The participating team must report to the In-Charge of the competition at least two hours before the presentation of the play.",
        "Decision of the panel of judges will be final and binding upon all.",
      ],
    },
    {
      name: "Elocution",
      rules: [
        "Each College will be represented by only one speaker.",
        "Medium of expression will be Hindi, English or Kannada.",
        "Each speaker will be allowed to speak for maximum five minutes.",
        "Subject / Topic of Elocution will be announced before the actual start of the competition. The item shall be prose or poetry and not song.",
        "The sequence of speakers will be decided by a draw of lots.",
        "The participating team must report to the In-Charge of the competition at least two hours before the presentation of the play.",
        "Decision of the panel of judges will be final and binding upon all.",
      ],
    },
    {
      name: "Debate",
      rules: [
        "Each Institute can send a team of two students, one will speak FOR, while another will speak AGAINST the motion.",
        "Medium of the debate will be in Hindi or English or Kannada.",
        "Topic of the Debate will be announced 24 hours in advance.",
        "Each speaker will be allowed to speak for maximum 5 minutes.",
        "The competitor from each College will speak FOR and AGAINST the motion. Paper reading is not allowed.",
        "The participating team must report to the In-Charge of the competition at least two hours before the presentation of the play.",
        "Decision of the panel of judges will be final and binding upon all.",
      ],
    },
  ],
  theatre: [
    {
      name: "One Act Play",
      rules: [
        "Only one entry shall be accepted from each Institution.",
        "Maximum 9 participants allowed per team.",
        "Maximum number of accompanists allowed is three.",
        "The duration of the play should not exceed 30minutes.",
        "Time will be counted as soon as the signal is given to start the play or to start the introduction, whichever is earlier. For stage setting and removal of set and properties, up to 10 minutes will be given after taking charge of the stage.",
        "The participating team shall bring their own set/ stage paraphernalia, make up materials, etc., light and general paraphernalia such as ordinary furniture which may be provided on advance information.",
        "Participants may speak in Hindi, English or kannada. In case the Language is regional one, the synopsis of the play with translation in English or Hindi must be submitted to the In-charge of the competition on the day of registration.",
        "Judgment will most likely be based on the qualities of the play like theme, work on acting, stage craft, design and general impression, etc.",
        "The participating team must report to the In-Charge of the competition at least two hours before the presentation of the play.",
        "Decision of the panel of judges will be final and binding upon all.",
        "Accompanists will either speak from the background or will play upon musical instruments for background music. They shall be required to appear on the stage.",
      ],
    },
    {
      name: "Skit",
      rules: [
        "Only one team per Institution is allowed.",
        "Maximum 6 participants allowed per team.",
        "Maximum number of accompanists allowed is Three.",
        "Maximum time allotted for each team is 8-10 minutes.",
        "Use of make-up, drapery and background music is allowed. No personal remarks, aspersions, character assassination, etc. is allowed.",
        "Participating team should submit 3 copies of the synopsis of the theme of the skit along with language of presentation (Hindi, English or Kannada) on the day of the registration.",
        "The presentation will be judged basically on the qualities like theme, work on acting, stage craft, design and general impression.",
        "Vulgarity or bitter insinuations in presentation should be avoided. Only innocent satire or humor is expected.",
        "The participating team must report to the In-Charge of the competition at least two hours before the presentation of the play.",
      ],
    },
    {
      name: "Mime",
      rules: [
        "Only one entry shall be accepted from each Institution.",
        "Maximum number of participants allowed are six.",
        "Maximum number of accompanists allowed is two.",
        "Judgment will be based on the qualities like idea, creativity of presentation, use of make-up, music and general impression.",
        "Maximum time allotted for each team is 4-6 minutes.",
        "The participating team must report to the In-Charge of the competition at least two hours before the presentation of the play.",
        "Decision of the panel of judges will be final and binding upon all.",
      ],
    },
    {
      name: "Mimicry",
      rules: [
        "Only one entry shall be accepted from each Institution.",
        "Each participant shall be given 5 minutes.",
        [
          "Participants may mimic sound of machines and speeches of well known persons etc. including film personalities.",
          "Marking will be based on:",
          [
            "Skill imitating",
            "Variety of sound and voices imitate.",
            "Presentation.",
          ],
        ],
        "The participating team must report to the In-Charge of the competition at least two hours before the presentation of the play.",
        "Decision of the panel of judges will be final.",
      ],
    },
  ],
  "fine-arts": [
    {
      name: "Collage",
      rules: [
        "Each College will be represented by one participant.",
        "Item will be conducted on the spot on the given topic/ subject, sheet size 15”x22”.",
        "Duration will not be more than 2 hours 30 minutes.",
        "Participants shall bring their own scissors, pasting and other material required for the contest.",
        "Collage has to be prepared from old magazines. The host institution will provide the drawing paper of the size 15” x 22”.",
        "The participating team must report to the In-Charge of the competition at least two hours before the presentation of the play.",
        "Decision of the panel of judges will be final and binding upon all.",
      ],
    },
    {
      name: "Installation",
      rules: [
        "Only one entry shall be accepted from each Institution with four participants.",
        "Duration will not be more than 2 hours 30 minutes.",
        "Item will be conducted on spot for which topic will be mentioned.",
        "Materials / Products should be brought by participants themselves.",
        "This item pertains to arrangements of unity in diversity of clearments inspired by material arrangements for which particular space will be provided.",
        "The participating team must report to the In-Charge of the competition at least two hours before the presentation of the play.",
        "Decision of the panel of judges will be final and binding upon all.",
      ],
    },
    {
      name: "On the Spot Painting",
      rules: [
        "Only one entry shall be accepted from each Institution.",
        "Item will be conducted on the spot and participants will be requested to do painting on the subject given by the In-charge(s) of the competition.",
        "Duration will not be more than 2 hours 30 minutes.",
        "Size of the painting will be half imperial size drawing paper i.e. 22 inches x 15 inches.",
        "Painting can be done in oil, water, poster or pastel colors.",
        "Candidate shall bring their own material like brushes, paints etc. only the paper/sheet will be provided by the host institute.",
        "The participating team must report to the In-Charge of the competition at least two hours before the presentation of the play.",
        "Decision of the panel of judges will be final and binding upon all.",
      ],
    },
    {
      name: "Poster Making",
      rules: [
        "Only one entry shall be accepted from each Institution.",
        "Item will be conducted on the spot and participants will be requested to do painting on the subject /topic/theme given by the In-charge of the competition.",
        "Duration will not be more than 2 hours 30 minutes.",
        "Participants shall bring their own material. Only the drawing paper/sheet 22” x15” will be provided by the Organizers.",
        "The participating team must report to the In-Charge of the competition at least two hours before the presentation of the play.",
        "Decision of the panel of judges will be final and binding upon all.",
      ],
    },
    {
      name: "Clay Modelling",
      rules: [
        "Only one entry shall be accepted from each Institution.",
        "Item will be conducted on the spot.",
        "Duration will not be more than 2 hours 30 minutes.",
        "Topics/size and other specific rules shall be announced on the spot.",
        "Clay shall be provided by the host institute.",
        "The participating team must report to the In-Charge of the competition at least two hours before the presentation of the play.",
        "Decision of the panel of judges will be final and binding upon all.",
      ],
    },
    {
      name: "Cartooning",
      rules: [
        "Only one entry shall be accepted from each Institution.",
        "Item will be conducted on the spot given subject/idea.",
        "Duration will not be more than 2 hour 30 minutes.",
        "Participants shall bring their own material. Only the drawing paper 22” x 15” will be provided by the host institution.",
        "The participating team must report to the In-Charge of the competition at least two hours before the presentation of the play.",
        "Decision of the panel of judges will be final and binding upon all.",
      ],
    },
    {
      name: "Rangoli",
      rules: [
        "Only one entry shall be accepted from each Institution.",
        "Duration will not be more than 2 hours 30 minutes.",
        "Participants shall bring their own material.",
        "The participants shall prepare a Rangoli within the space provided by the organizers.",
        "The participating team must report to the In-Charge of the competition at least two hours before the presentation of the play.",
        "Decision of the panel of judges will be final and binding upon all.",
      ],
    },
    {
      name: "Spot Photography",
      rules: [
        "Only one entry shall be accepted from each Institution.",
        "The participant has to bring his/her own digital camera of not more than 16 Mega Pixel.",
        "The digital camera should have a memory card which will be formatted by the judges before the commencement of the contest.",
        "The time will be2 hour 30 minutes.",
        "The participant has to capture 5 photographs on the theme announced on the spot by the judges.",
        "No mixing, matching or morphing of photographs will be permitted.",
        "Software such as Photoshop, etc. for enhancing images is not permitted.",
        "The organizers will have all rights for the use of these pictures as and when they deem fit.",
        "Digital images are evaluated on the basis of – (i) IMPACT (ii) COMPOSITION (iii) TECHNICAL QUALITY and (iv) SUITABILITY for the specific theme.",
        "The additional instructions will be announced on the spot.",
        "The participating team must report to the In-Charge of the competition at least two hours before the presentation of the play.",
        "Decision of the panel of judges will be final and binding upon all.",
      ],
    },
  ],
};
export default rules;
