const guidelines = {
  music: [
    {
      name: "Classical Vocal Solo (Hindustani/Karnataka)",
      p: 1,
      a: 2,
      minTime: 10,
      maxTime: 15,
    },
    {
      name: "Classical Instrumental Solo (Percussion Tal Vadya)",
      p: 1,
      a: 2,
      minTime: 10,
      maxTime: 15,
    },
    {
      name: "Light Vocal (India)",
      p: 1,
      a: 2,
      minTime: 10,
      maxTime: 15,
    },
    {
      name: "Classical Instrumental Solo (Non-Precussion Swar Vadya)",
      p: 1,
      a: 2,
      minTime: 10,
      maxTime: 15,
    },
    {
      name: "Western Vocal (Solo)",
      p: 1,
      a: 2,
      minTime: 10,
      maxTime: 15,
    },
    {
      name: "Group Song (Indian)",
      p: 1,
      a: 2,
      minTime: 10,
      maxTime: 15,
    },
    {
      name: "Group Song (Western)",
      p: 1,
      a: 2,
      minTime: 10,
      maxTime: 15,
    },
    {
      name: "Flok Orchestra",
      p: 1,
      a: 2,
      minTime: 10,
      maxTime: 15,
    },
  ],
  dance: [
    {
      name: "Folk / Tribal Dance",
      p: 1,
      a: 2,
      minTime: 10,
      maxTime: 15,
    },
    {
      name: "Classical Dance (Indian)",
      p: 1,
      a: 2,
      minTime: 10,
      maxTime: 15,
    },
  ],
  literary: [
    {
      name: "Quiz",
      p: 1,
      a: 2,
      minTime: 10,
      maxTime: 15,
    },
    {
      name: "Elocution",
      p: 1,
      a: 2,
      minTime: 10,
      maxTime: 15,
    },
    {
      name: "Debate",
      p: 1,
      a: 2,
      minTime: 10,
      maxTime: 15,
    },
  ],
  theatre: [
    {
      name: "One Act Play",
      p: 1,
      a: 2,
      minTime: 10,
      maxTime: 15,
    },
    {
      name: "Skit",
      p: 1,
      a: 2,
      minTime: 10,
      maxTime: 15,
    },
    {
      name: "Mime",
      p: 1,
      a: 2,
      minTime: 10,
      maxTime: 15,
    },
    {
      name: "Mimicry",
      p: 1,
      a: 2,
      minTime: 10,
      maxTime: 15,
    },
  ],
  "fine-arts": [
    {
      name: "Collage",
      p: 1,
      a: 2,
      minTime: 10,
      maxTime: 15,
    },
    {
      name: "Installation",
      p: 1,
      a: 2,
      minTime: 10,
      maxTime: 15,
    },
    {
      name: "On the Spot Painting",
      p: 1,
      a: 2,
      minTime: 10,
      maxTime: 15,
    },
    {
      name: "Poster Making",
      p: 1,
      a: 2,
      minTime: 10,
      maxTime: 15,
    },
    {
      name: "Clay Modelling",
      p: 1,
      a: 2,
      minTime: 10,
      maxTime: 15,
    },
    {
      name: "Cartooning",
      p: 1,
      a: 2,
      minTime: 10,
      maxTime: 15,
    },
    {
      name: "Rangoli",
      p: 1,
      a: 2,
      minTime: 10,
      maxTime: 15,
    },
    {
      name: "Spot Photography",
      p: 1,
      a: 2,
      minTime: 10,
      maxTime: 15,
    },
  ],
};
export default guidelines;
